name: kapatidsync
description: "a flutter app that will help the chruch officer, how many attendancces are absences."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.1
  firebase_core : ^3.6.0
  cloud_firestore: ^5.6.5
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ico/ic_launcher.png"
  adaptive_icon_background: "assets/ico/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/ico/ic_launcher_foreground.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true


  assets:
    - assets/ico/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: BigShouldersInline
      fonts:
        - asset: assets/fonts/BigShouldersInline_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/BigShouldersInline_36pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/BigShouldersInline_18pt-Black.ttf
          weight: 900

